### ISSUE TITLE
"model_train.py" cannot find

### ISSUE THREAD

**Issue by iceshade000** [KaiyuanZh/OrthogLinearBackdoor#3]
Thank you for open source. I want to train the model in `ckpt` from scratch, but cannot find "model_train.py" , can you provide this file?

**Comment by KaiyuanZh** [comment]
Thank you for pointing that out! I've added the `model_train.py` file to the repository. Please check it out and let me know if you encounter any issues.

**Comment by iceshade000** [comment]
Very helpful，it works!
Moreover, since 366 os.environ['CUDA_VISIBLE_DEVICES'] = args.gpu, 369 DEVICE = torch.device(f'cuda:{args.gpu}') should be  DEVICE = torch.device('cuda'),  otherwise if gpu!=0, CUDA error: invalid device ordinal CUDA kernel errors

**Comment by KaiyuanZh** [comment]
Glad this helps! Thanks again for reporting this. I've fixed the file.
